theme: jekyll-theme-slate

site_name: nemieducationalforum
repo_url: https://nemieducationalforum.github.io/nemieducationalforum/
repo_name: source
edit_uri: edit/master/
site_description: |
  
nav:
  - Intro: 'README.md'
  - Complex Numbers: 'seminars.md'


markdown_extensions:
  - mdx_math:
      enable_dollar_delimiter: True
  - toc:
      permalink: True
  - admonition
  - pymdownx.details
  - pymdownx.extra
  - pymdownx.emoji
  - abbr
  - footnotes
  - meta

extra_css:
  - 'https://use.fontawesome.com/releases/v5.8.1/css/all.css'
  - 'styles/thebelab.css'

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.3/MathJax.js?config=TeX-AMS_HTML'
  - 'scripts/thebelab-custom.js'
  - 'scripts/mathjaxhelper.js'
  - 'scripts/thebelabhelper.js'
